apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  selector:
    matchLabels:
      app: $name
  template:
    spec:
      containers:
      - name: name
        image: REPLACEME 
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: $name