apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage
  labels:
    app: storage
spec:
  selector:
    matchLabels:
      app: storage
  template:
    metadata:
      labels:
        app: storage
        tier: backend
    spec:
      containers:
      - name: storage
        image: storage
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: "10m"
---
apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
spec:
  ports:
    - port: 80
      targetPort: 8081
      protocol: TCP
  selector:
    app: storage
